version: "3.3"
services:
  didactica:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    container_name: didactica
    environment: 
      - MOD_SECURITY=on
