apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  name: {{ include "my-app.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ include  "my-app.image_name" . }}
        imagePullPolicy: Always
        name: {{ include "my-app.name" . }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.hpa.cpuTarget }}
            memory: {{ .Values.hpa.memTarget }}
          limits:
            cpu: {{ .Values.hpa.cpuLimit }}
            memory: {{ .Values.hpa.memLimit }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: "/usr/local/src/.well-known"
            name: "{{ include "my-app.fullname" . }}-domain-verification"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: "{{ include "my-app.fullname" . }}-domain-verification"
        configMap:
          name: "{{ include "my-app.fullname" . }}-domain-verification"
          defaultMode: 420
  test: false
  triggers:
  - type: ConfigChange