{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-app.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: {{ include "my-app.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: 80
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      stabilizationWindowSeconds: 0
{{ end }} 
