{{- if .Values.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.custom_host.enabled }}
  host: {{ .Values.route.custom_host.name }}
  {{ end }}
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ include "my-app.fullname" . }}
    weight: 100
  wildcardPolicy: None
  {{- if .Values.route.https_redirect }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  {{ end }}
{{ end }}
